server:
  port: 9000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: EDU-VIDEO
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

oss:
  accessKeyId: LTAI4G2Gy8wMyYgGJAQXU7G8
  accessKeySecret: RFoXrL0ECnS5QETFRC833s5fYSzHYk


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/